### ISSUE TITLE
Test bedtools commands for merging existing annotation sources

### ISSUE THREAD

**Issue by rdocking** [rdocking/fusebench#42]
Taking as input BEDPE-formatted output from the available annotation sources created in previous tickets, test `bedtools` subcommands for generating a merged annotation source file.

**Comment by wilcas** [comment]
Should I just report a generic command here with a plan for standardization/merging fields?

**Comment by rdocking** [comment]
For now, even some example command syntax and some comments on how well it seems to work / not work would be great. If this works well, it will be a good way to move forward relatively quickly. If it doesn't, we'll need to rethink things.

**Comment by wilcas** [comment]
The basic `bedtools intersect` command would allow us to easily see which features are shared between databases, but preserving the annotations would be odd. with `bedtools map` we can combine 2 files at a time and specify how to combine overlapping features (both categorical and continuous/numerical fields). The problem here is that it doesn't seem to support combining more than 2 files at a time.

We could just generically merge the files with bedops:
` bedops --everything file1 file2 ... filen > merged.bedpe` 

From there, we can specify columns to combine using bedtools merge:
`bedtools merge merged.bedpe -c x,y -o operation_on_x,operation_on_y` 

I will spend a little more time looking at `bedops`, since it seems more robust to merging data in columns in a generic way.

**Comment by wilcas** [comment]
Okay I found a tool that's meant for the purpose of comparing BEDPE files: http://bedtools.readthedocs.io/en/latest/content/tools/pairtopair.html
